// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import CoreBluetooth;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURL;
@class UIImage;
@class NSCoder;

SWIFT_CLASS("_TtC6ilocky11AsyncButton")
@interface AsyncButton : UIButton
- (void)setImageURL:(NSURL * _Nullable)url placeholderImage:(UIImage * _Nullable)placeholder forState:(UIControlState)state;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14AsyncImageView")
@interface AsyncImageView : UIImageView
@property (nonatomic, strong) UIImage * _Nullable placeholderImage;
@property (nonatomic, strong) NSURL * _Nullable url;
- (void)setURL:(NSURL * _Nullable)url placeholderImage:(UIImage * _Nullable)placeholderImage;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC6ilocky12AutoTextView")
@interface AutoTextView : UITextView
- (CGSize)intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class CALayer;

SWIFT_PROTOCOL("_TtP6ilocky10Springable_")
@protocol Springable
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic, readonly, strong) CALayer * _Nonnull layer;
@property (nonatomic) CGAffineTransform transform;
@property (nonatomic) CGFloat alpha;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
@end


SWIFT_CLASS("_TtC6ilocky12SpringButton")
@interface SpringButton : UIButton <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC6ilocky16DesignableButton")
@interface DesignableButton : SpringButton
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15SpringImageView")
@interface SpringImageView : UIImageView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky19DesignableImageView")
@interface DesignableImageView : SpringImageView
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky11SpringLabel")
@interface SpringLabel : UILabel <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15DesignableLabel")
@interface DesignableLabel : SpringLabel
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15SpringTextField")
@interface SpringTextField : UITextField <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky19DesignableTextField")
@interface DesignableTextField : SpringTextField
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;
@property (nonatomic) CGFloat sidePadding;
@property (nonatomic) CGFloat leftPadding;
@property (nonatomic) CGFloat rightPadding;
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14SpringTextView")
@interface SpringTextView : UITextView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky18DesignableTextView")
@interface DesignableTextView : SpringTextView
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky10SpringView")
@interface SpringView : UIView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * _Nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * _Nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14DesignableView")
@interface DesignableView : SpringView
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ILockyPassport;

SWIFT_CLASS("_TtC6ilocky6Device")
@interface Device : NSObject
+ (NSInteger)AM;
+ (NSInteger)IB;
+ (NSString * _Null_unspecified)NAME_PREF;
+ (NSString * _Null_unspecified)NAME;
+ (NSString * _Null_unspecified)ILOCKY_ID;
+ (NSString * _Null_unspecified)MACADDR;
+ (NSString * _Null_unspecified)FW_VERSION;
+ (NSString * _Null_unspecified)STARRED;
+ (NSString * _Null_unspecified)CREATED_TIME;
+ (NSString * _Null_unspecified)TYPE_AM;
+ (NSString * _Null_unspecified)TYPE_IB;
@property (nonatomic, copy) NSString * _Nonnull iLocky_id;
@property (nonatomic, copy) NSString * _Nonnull MACAddr;
@property (nonatomic, copy) NSString * _Nonnull fwVersion;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) BOOL alwaysBeacon;
@property (nonatomic) NSInteger type;
- (nonnull instancetype)initWithILocky_id:(NSString * _Nonnull)iLocky_id type:(NSInteger)type name:(NSString * _Nonnull)name MACAddr:(NSString * _Nonnull)MACAddr fwVersion:(NSString * _Nonnull)fwVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithILocky_id:(NSString * _Nonnull)iLocky_id type:(NSInteger)type name:(NSString * _Nonnull)name MACAddr:(NSString * _Nonnull)MACAddr fwVersion:(NSString * _Nonnull)fwVersion alwaysBeacon:(BOOL)alwaysBeacon OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)getName;
+ (Device * _Nullable)bluetoothNameToiLockyDevice:(NSString * _Nullable)peripheralName;
- (NSString * _Nonnull)getOpenDoorCommand:(ILockyPassport * _Nonnull)passport;
- (NSInteger)getThreshould;
- (BOOL)isAESEnabled;
@end

@protocol ILockyViewControllerCallback;
@protocol ILockyEventDelegate;
@class NSString;

SWIFT_CLASS("_TtC6ilocky6ILocky")
@interface ILocky : NSObject
+ (id <ILockyViewControllerCallback> _Nullable)iLockyViewControllerCallback;
+ (void)setILockyViewControllerCallback:(id <ILockyViewControllerCallback> _Nullable)value;
+ (BOOL)success;
+ (void)setSuccess:(BOOL)value;
+ (BOOL)isForegroundAccessSuccess;
+ (ILockyPassport * _Nullable)usedILockyPassport;
+ (void)setUsedILockyPassport:(ILockyPassport * _Nullable)value;
+ (void)setLanguage:(NSString * _Nonnull)lang;
+ (void)setAdsImageURLTracking:(UIImage * _Nonnull)image url:(NSURL * _Nonnull)url tracking:(NSString * _Nonnull)tracking;
+ (void)setBackground:(BOOL)isBackground keepScan:(BOOL)keepScan;
+ (void)setBackground:(BOOL)isBackground;
+ (void)setDetailTrackEnable:(BOOL)detail;
+ (void)setEventDelegate:(id <ILockyEventDelegate> _Nonnull)delegate;
+ (void)track:(NSString * _Nonnull)event;
+ (void)trackWaitTime:(ILockyPassport * _Nonnull)passport success:(BOOL)success wait_time:(NSInteger)wait_time;
+ (void)track:(NSString * _Nonnull)event prop:(NSDictionary<NSString *, id> * _Null_unspecified)prop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6ilocky31ILockyAlwaysBeaconEventCallback_")
@protocol ILockyAlwaysBeaconEventCallback
- (void)onPassportCanBeUsed:(ILockyPassport * _Nonnull)passport;
- (void)onPassportCanNotBeUsed:(ILockyPassport * _Nonnull)passport;
@end

@class CBCentralManager;
@class CBPeripheral;
@class NSNumber;
@class NSError;
@class CBService;
@class CBCharacteristic;
@class CBPeripheralManager;

SWIFT_CLASS("_TtC6ilocky16ILockyBLEManager")
@interface ILockyBLEManager : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate, CBPeripheralManagerDelegate>
@property (nonatomic) BOOL keepScan;
@property (nonatomic, strong) id <ILockyEventDelegate> _Nullable iLockyEventDelegate;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
- (void)peripheralManager:(CBPeripheralManager * _Nonnull)_peripheral willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
- (void)peripheralManagerDidUpdateState:(CBPeripheralManager * _Nonnull)peripheral;
@end


SWIFT_PROTOCOL("_TtP6ilocky19ILockyEventDelegate_")
@protocol ILockyEventDelegate
- (void)onDeviceUnauthorized;
- (void)onPassportUsed:(ILockyPassport * _Nonnull)passport;
- (void)onILockyAccessSuccess:(ILockyPassport * _Nonnull)passport;
- (void)onILockyAccessFail:(ILockyPassport * _Nonnull)passport;
- (void)onNotCloseEnough;
@end

@class NSData;

SWIFT_CLASS("_TtC6ilocky14ILockyPassport")
@interface ILockyPassport : NSObject
+ (NSString * _Null_unspecified)DEFAULT_PASSPORT_NAME;
+ (NSString * _Null_unspecified)ILockyPassportErrorDomain;
+ (NSString * _Null_unspecified)ACTION_TYPE;
+ (NSString * _Null_unspecified)PASSPORT_NAME;
+ (NSString * _Null_unspecified)ILOCKY_ID;
+ (NSString * _Null_unspecified)DEVICE_UUID;
+ (NSString * _Null_unspecified)START_TIME;
+ (NSString * _Null_unspecified)END_TIME;
+ (NSString * _Null_unspecified)TIMES_LIMIT;
+ (NSString * _Null_unspecified)TIMES;
+ (NSString * _Null_unspecified)REVOKE_PAST;
+ (NSString * _Null_unspecified)SIGNATURE;
+ (NSString * _Null_unspecified)VALID;
+ (NSString * _Null_unspecified)LAST_TIME_STAMP;
+ (NSString * _Null_unspecified)DURATION;
+ (NSString * _Null_unspecified)USER_TAG;
+ (NSString * _Null_unspecified)ILOCKY_NAME;
+ (NSString * _Null_unspecified)SERVER_PASSPORT;
+ (NSString * _Null_unspecified)SERVER_PASSPORT_ID;
+ (NSString * _Null_unspecified)SERVER_ILOCKY_ID;
+ (NSString * _Null_unspecified)SERVER_DEVICE_UUID;
+ (NSString * _Null_unspecified)SERVER_START_TIME;
+ (NSString * _Null_unspecified)SERVER_END_TIME;
+ (NSString * _Null_unspecified)SERVER_TIMES_LIMIT;
+ (NSString * _Null_unspecified)SERVER_REVOKE_LEGACY;
+ (NSString * _Null_unspecified)SERVER_RFID_DURATION;
+ (NSString * _Null_unspecified)SERVER_SIGNATURE;
+ (NSString * _Null_unspecified)SERVER_PASSPORT_NAME;
+ (NSString * _Null_unspecified)SERVER_USER_TAG;
+ (NSString * _Null_unspecified)SERVER_ILOCKY_NAME;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE_LOW_SECURITY_OPEN;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE_DFU_OTA;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE_INITIAL;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE_RESET;
+ (NSString * _Null_unspecified)SERVER_ACTION_TYPE_FACTORY_RESET;
+ (ILockyPassport * _Nonnull)Builder;
- (ILockyPassport * _Nonnull)setUserTag:(NSString * _Nullable)tag;
- (ILockyPassport * _Nonnull)setILockyName:(NSString * _Nullable)name;
- (ILockyPassport * _Nonnull)setActionType:(NSInteger)type;
- (ILockyPassport * _Nonnull)setPassportName:(NSString * _Nullable)name;
- (ILockyPassport * _Nonnull)setDeviceId:(NSString * _Nonnull)id;
- (ILockyPassport * _Nonnull)setILockyId:(NSString * _Nonnull)id;
- (ILockyPassport * _Nonnull)setStartTime:(int64_t)time;
- (ILockyPassport * _Nonnull)setEndTime:(int64_t)time;
- (ILockyPassport * _Nonnull)setTimes:(NSInteger)times;
- (ILockyPassport * _Nonnull)setRevokePast:(BOOL)revoke;
- (ILockyPassport * _Nonnull)setSignature:(NSString * _Nonnull)signature;
- (ILockyPassport * _Nonnull)setDuration:(NSInteger)durationInMilli;
- (NSString * _Null_unspecified)getUserTag;
- (NSString * _Null_unspecified)getILockyName;
- (NSString * _Null_unspecified)getILockyID;
- (NSString * _Nullable)getPassportName;
- (NSInteger)getActionType;
- (NSInteger)getTimes;
- (NSInteger)getTimesLimit;
- (int64_t)getStartTime;
- (int64_t)getEndTime;
- (NSInteger)getDuration;
- (NSString * _Nonnull)getSignature;
- (NSString * _Nonnull)toJSONString;
+ (NSArray<ILockyPassport *> * _Nonnull)getAlliLockyPassports;
+ (void)initialize;
+ (void)refreshValidStatus;
+ (NSString * _Nonnull)getDeviceUuid;
+ (BOOL)isValidPassportIn;
+ (void)flush;
+ (void)removeAllPassports;
+ (void)removeAllInvalidPassports;
+ (void)importILockyPassport:(ILockyPassport * _Nonnull)iLockyPassport error:(NSError * _Nullable * _Null_unspecified)error;
+ (ILockyPassport * _Nullable)getValidAndCopyPassport:(ILockyPassport * _Nonnull)passport;
+ (ILockyPassport * _Nullable)getValidPassport:(NSString * _Nonnull)iLocky_id;
- (BOOL)isValid;
+ (BOOL)removePassport:(ILockyPassport * _Null_unspecified)passport;
- (NSData * _Null_unspecified)getPassportPacket:(NSInteger)num;
- (BOOL)isSame:(ILockyPassport * _Nonnull)passport;
+ (void)importPassport:(NSString * _Nonnull)content error:(NSError * _Nullable * _Null_unspecified)error;
@end


SWIFT_PROTOCOL("_TtP6ilocky28ILockyViewControllerCallback_")
@protocol ILockyViewControllerCallback
- (void)onDismiss:(BOOL)success;
@end


SWIFT_CLASS("_TtC6ilocky24KeyboardLayoutConstraint")
@interface KeyboardLayoutConstraint : NSLayoutConstraint
- (void)awakeFromNib;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky11LoadingView")
@interface LoadingView : UIView
@property (nonatomic, weak) IBOutlet SpringView * _Null_unspecified indicatorView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky6Spring")
@interface Spring : NSObject
- (void)animate;
- (void)animateNext:(void (^ _Nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ _Nonnull)(void))completion;
- (void)customAwakeFromNib;
- (void)customLayoutSubviews;
@end


SWIFT_CLASS("_TtC6ilocky15SpringAnimation")
@interface SpringAnimation : NSObject
+ (void)spring:(NSTimeInterval)duration animations:(void (^ _Nonnull)(void))animations;
+ (void)springEaseIn:(NSTimeInterval)duration animations:(void (^ _Null_unspecified)(void))animations;
+ (void)springEaseOut:(NSTimeInterval)duration animations:(void (^ _Null_unspecified)(void))animations;
+ (void)springEaseInOut:(NSTimeInterval)duration animations:(void (^ _Null_unspecified)(void))animations;
+ (void)springLinear:(NSTimeInterval)duration animations:(void (^ _Null_unspecified)(void))animations;
+ (void)springWithDelay:(NSTimeInterval)duration delay:(NSTimeInterval)delay animations:(void (^ _Null_unspecified)(void))animations;
+ (void)springWithCompletion:(NSTimeInterval)duration animations:(void (^ _Null_unspecified)(void))animations completion:(void (^ _Null_unspecified)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








@protocol UIViewControllerContextTransitioning;
@class UIViewController;

SWIFT_CLASS("_TtC6ilocky17TransitionManager")
@interface TransitionManager : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14TransitionZoom")
@interface TransitionZoom : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(ilocky))
- (nonnull instancetype)initWithHex:(NSString * _Nonnull)hex;
@end


@interface UIImage (SWIFT_EXTENSION(ilocky))
@end


@interface UIView (SWIFT_EXTENSION(ilocky))
- (void)showLoading;
- (void)hideLoading;
@end

@class UIStoryboardSegue;

@interface UIViewController (SWIFT_EXTENSION(ilocky))
- (IBAction)unwindToViewController:(UIStoryboardSegue * _Nonnull)sender;
@end

#pragma clang diagnostic pop
