// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import CoreBluetooth;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURL;
@class UIImage;
@class NSCoder;

SWIFT_CLASS("_TtC6ilocky11AsyncButton")
@interface AsyncButton : UIButton
- (void)setImageURL:(NSURL * __nullable)url placeholderImage:(UIImage * __nullable)placeholder forState:(UIControlState)state;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14AsyncImageView")
@interface AsyncImageView : UIImageView
@property (nonatomic, strong) UIImage * __nullable placeholderImage;
@property (nonatomic, strong) NSURL * __nullable url;
- (void)setURL:(NSURL * __nullable)url placeholderImage:(UIImage * __nullable)placeholderImage;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC6ilocky12AutoTextView")
@interface AutoTextView : UITextView
- (CGSize)intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class CALayer;

SWIFT_PROTOCOL("_TtP6ilocky10Springable_")
@protocol Springable
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic, readonly, strong) CALayer * __nonnull layer;
@property (nonatomic) CGAffineTransform transform;
@property (nonatomic) CGFloat alpha;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
@end


SWIFT_CLASS("_TtC6ilocky12SpringButton")
@interface SpringButton : UIButton <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC6ilocky16DesignableButton")
@interface DesignableButton : SpringButton
@property (nonatomic, strong) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * __nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15SpringImageView")
@interface SpringImageView : UIImageView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky19DesignableImageView")
@interface DesignableImageView : SpringImageView
@property (nonatomic, strong) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * __nullable)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky11SpringLabel")
@interface SpringLabel : UILabel <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15DesignableLabel")
@interface DesignableLabel : SpringLabel
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky15SpringTextField")
@interface SpringTextField : UITextField <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky19DesignableTextField")
@interface DesignableTextField : SpringTextField
@property (nonatomic, strong) UIColor * __nonnull placeholderColor;
@property (nonatomic) CGFloat sidePadding;
@property (nonatomic) CGFloat leftPadding;
@property (nonatomic) CGFloat rightPadding;
@property (nonatomic, strong) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14SpringTextView")
@interface SpringTextView : UITextView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky18DesignableTextView")
@interface DesignableTextView : SpringTextView
@property (nonatomic, strong) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky10SpringView")
@interface SpringView : UIView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14DesignableView")
@interface DesignableView : SpringView
@property (nonatomic, strong) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * __nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ILockyPassport;

SWIFT_CLASS("_TtC6ilocky6Device")
@interface Device : NSObject
+ (NSInteger)AM;
+ (NSInteger)IB;
+ (NSString * __null_unspecified)NAME_PREF;
+ (NSString * __null_unspecified)NAME;
+ (NSString * __null_unspecified)ILOCKY_ID;
+ (NSString * __null_unspecified)MACADDR;
+ (NSString * __null_unspecified)FW_VERSION;
+ (NSString * __null_unspecified)STARRED;
+ (NSString * __null_unspecified)CREATED_TIME;
+ (NSString * __null_unspecified)TYPE_AM;
+ (NSString * __null_unspecified)TYPE_IB;
@property (nonatomic, copy) NSString * __nonnull iLocky_id;
@property (nonatomic, copy) NSString * __nonnull MACAddr;
@property (nonatomic, copy) NSString * __nonnull fwVersion;
@property (nonatomic, copy) NSString * __nullable name;
@property (nonatomic) BOOL alwaysBeacon;
@property (nonatomic) NSInteger type;
- (nonnull instancetype)initWithILocky_id:(NSString * __nonnull)iLocky_id type:(NSInteger)type name:(NSString * __nonnull)name MACAddr:(NSString * __nonnull)MACAddr fwVersion:(NSString * __nonnull)fwVersion OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithILocky_id:(NSString * __nonnull)iLocky_id type:(NSInteger)type name:(NSString * __nonnull)name MACAddr:(NSString * __nonnull)MACAddr fwVersion:(NSString * __nonnull)fwVersion alwaysBeacon:(BOOL)alwaysBeacon OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nullable)getName;
+ (Device * __nullable)bluetoothNameToiLockyDevice:(NSString * __nullable)peripheralName;
- (NSString * __nonnull)getOpenDoorCommand:(ILockyPassport * __nonnull)passport;
- (NSInteger)getThreshould;
@end

@protocol ILockyEventDelegate;
@class NSString;

SWIFT_CLASS("_TtC6ilocky6ILocky")
@interface ILocky : NSObject
+ (void)setLanguage:(NSString * __nonnull)lang;
+ (void)setAdsImageURLTracking:(UIImage * __nonnull)image url:(NSURL * __nonnull)url tracking:(NSString * __nonnull)tracking;
+ (void)setBackground:(BOOL)isBackground keepScan:(BOOL)keepScan;
+ (void)setBackground:(BOOL)isBackground;
+ (void)setEventDelegate:(id <ILockyEventDelegate> __nonnull)delegate;
+ (void)track:(NSString * __nonnull)event;
+ (void)trackWaitTime:(ILockyPassport * __nonnull)passport success:(BOOL)success wait_time:(NSInteger)wait_time;
+ (void)track:(NSString * __nonnull)event prop:(NSDictionary<NSString *, id> * __null_unspecified)prop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6ilocky31ILockyAlwaysBeaconEventCallback_")
@protocol ILockyAlwaysBeaconEventCallback
- (void)onPassportCanBeUsed:(ILockyPassport * __nonnull)passport;
- (void)onPassportCanNotBeUsed:(ILockyPassport * __nonnull)passport;
@end

@class CBCentralManager;
@class CBPeripheral;
@class NSNumber;
@class NSError;
@class CBService;
@class CBCharacteristic;
@class CBPeripheralManager;

SWIFT_CLASS("_TtC6ilocky16ILockyBLEManager")
@interface ILockyBLEManager : NSObject <CBPeripheralManagerDelegate, CBCentralManagerDelegate, CBPeripheralDelegate>
@property (nonatomic) BOOL keepScan;
@property (nonatomic, strong) id <ILockyEventDelegate> __nullable iLockyEventDelegate;
- (void)centralManager:(CBCentralManager * __nonnull)central didDiscoverPeripheral:(CBPeripheral * __nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * __nonnull)advertisementData RSSI:(NSNumber * __nonnull)RSSI;
- (void)centralManager:(CBCentralManager * __nonnull)central didConnectPeripheral:(CBPeripheral * __nonnull)peripheral;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didDiscoverServices:(NSError * __nullable)error;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * __nonnull)service error:(NSError * __nullable)error;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * __nonnull)characteristic error:(NSError * __nullable)error;
- (void)centralManagerDidUpdateState:(CBCentralManager * __nonnull)central;
- (void)centralManager:(CBCentralManager * __nonnull)central didFailToConnectPeripheral:(CBPeripheral * __nonnull)peripheral error:(NSError * __nullable)error;
- (void)centralManager:(CBCentralManager * __nonnull)central willRestoreState:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)peripheralManager:(CBPeripheralManager * __nonnull)_peripheral willRestoreState:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)peripheralManagerDidUpdateState:(CBPeripheralManager * __nonnull)peripheral;
@end


SWIFT_PROTOCOL("_TtP6ilocky19ILockyEventDelegate_")
@protocol ILockyEventDelegate
- (void)onDeviceUnauthorized;
- (void)onPassportUsed:(ILockyPassport * __nonnull)passport;
- (void)onILockyAccessSuccess:(ILockyPassport * __nonnull)passport;
- (void)onILockyAccessFail:(ILockyPassport * __nonnull)passport;
- (void)onNotCloseEnough;
@end


SWIFT_CLASS("_TtC6ilocky14ILockyPassport")
@interface ILockyPassport : NSObject
+ (NSString * __null_unspecified)DEFAULT_PASSPORT_NAME;
+ (NSString * __null_unspecified)ILockyPassportErrorDomain;
+ (NSString * __null_unspecified)ACTION_TYPE;
+ (NSString * __null_unspecified)PASSPORT_NAME;
+ (NSString * __null_unspecified)ILOCKY_ID;
+ (NSString * __null_unspecified)DEVICE_UUID;
+ (NSString * __null_unspecified)START_TIME;
+ (NSString * __null_unspecified)END_TIME;
+ (NSString * __null_unspecified)TIMES_LIMIT;
+ (NSString * __null_unspecified)TIMES;
+ (NSString * __null_unspecified)REVOKE_PAST;
+ (NSString * __null_unspecified)SIGNATURE;
+ (NSString * __null_unspecified)VALID;
+ (NSString * __null_unspecified)LAST_TIME_STAMP;
+ (NSString * __null_unspecified)DURATION;
+ (NSString * __null_unspecified)SERVER_PASSPORT;
+ (NSString * __null_unspecified)SERVER_PASSPORT_ID;
+ (NSString * __null_unspecified)SERVER_ILOCKY_ID;
+ (NSString * __null_unspecified)SERVER_DEVICE_UUID;
+ (NSString * __null_unspecified)SERVER_START_TIME;
+ (NSString * __null_unspecified)SERVER_END_TIME;
+ (NSString * __null_unspecified)SERVER_TIMES_LIMIT;
+ (NSString * __null_unspecified)SERVER_REVOKE_LEGACY;
+ (NSString * __null_unspecified)SERVER_RFID_DURATION;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_LOW_SECURITY_OPEN;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_DFU_OTA;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_INITIAL;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_RESET;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_FACTORY_RESET;
+ (ILockyPassport * __nonnull)Builder;
- (ILockyPassport * __nonnull)setActionType:(NSInteger)type;
- (ILockyPassport * __nonnull)setPassportName:(NSString * __nonnull)name;
- (ILockyPassport * __nonnull)setDeviceId:(NSString * __nonnull)id;
- (ILockyPassport * __nonnull)setILockyId:(NSString * __nonnull)id;
- (ILockyPassport * __nonnull)setStartTime:(int64_t)time;
- (ILockyPassport * __nonnull)setEndTime:(int64_t)time;
- (ILockyPassport * __nonnull)setTimes:(NSInteger)times;
- (ILockyPassport * __nonnull)setRevokePast:(BOOL)revoke;
- (ILockyPassport * __nonnull)setSignature:(NSString * __nonnull)signature;
- (ILockyPassport * __nonnull)setDuration:(NSInteger)durationInMilli;
- (NSString * __null_unspecified)getILockyID;
- (NSString * __nullable)getPassportName;
- (NSInteger)getActionType;
- (NSInteger)getTimes;
- (NSInteger)getTimesLimit;
- (int64_t)getStartTime;
- (int64_t)getEndTime;
- (NSInteger)getDuration;
- (NSString * __nonnull)toJSONString;
+ (NSArray<ILockyPassport *> * __nonnull)getAlliLockyPassports;
+ (void)initialize;
+ (void)refreshValidStatus;
+ (NSString * __nonnull)getDeviceUuid;
+ (BOOL)isValidPassportIn;
+ (void)flush;
+ (void)removeAllInvalidPassports;
+ (void)importILockyPassport:(ILockyPassport * __nonnull)iLockyPassport error:(NSError * __nullable * __null_unspecified)error;
+ (ILockyPassport * __nullable)getValidAndCopyPassport:(ILockyPassport * __nonnull)passport;
+ (ILockyPassport * __nullable)getValidPassport:(NSString * __nonnull)iLocky_id;
- (BOOL)isValid;
+ (BOOL)removePassport:(ILockyPassport * __null_unspecified)passport;
- (BOOL)isSame:(ILockyPassport * __nonnull)passport;
+ (void)importPassport:(NSString * __nonnull)content error:(NSError * __nullable * __null_unspecified)error;
@end


SWIFT_CLASS("_TtC6ilocky24KeyboardLayoutConstraint")
@interface KeyboardLayoutConstraint : NSLayoutConstraint
- (void)awakeFromNib;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky11LoadingView")
@interface LoadingView : UIView
@property (nonatomic, weak) IBOutlet SpringView * __null_unspecified indicatorView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky6Spring")
@interface Spring : NSObject
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (void)customAwakeFromNib;
- (void)customLayoutSubviews;
@end


SWIFT_CLASS("_TtC6ilocky15SpringAnimation")
@interface SpringAnimation : NSObject
+ (void)spring:(NSTimeInterval)duration animations:(void (^ __nonnull)(void))animations;
+ (void)springEaseIn:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springEaseOut:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springEaseInOut:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springLinear:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springWithDelay:(NSTimeInterval)duration delay:(NSTimeInterval)delay animations:(void (^ __null_unspecified)(void))animations;
+ (void)springWithCompletion:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations completion:(void (^ __null_unspecified)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








@protocol UIViewControllerContextTransitioning;
@class UIViewController;

SWIFT_CLASS("_TtC6ilocky17TransitionManager")
@interface TransitionManager : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> __nullable)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForPresentedController:(UIViewController * __nonnull)presented presentingController:(UIViewController * __nonnull)presenting sourceController:(UIViewController * __nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForDismissedController:(UIViewController * __nonnull)dismissed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ilocky14TransitionZoom")
@interface TransitionZoom : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> __nullable)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForPresentedController:(UIViewController * __nonnull)presented presentingController:(UIViewController * __nonnull)presenting sourceController:(UIViewController * __nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForDismissedController:(UIViewController * __nonnull)dismissed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(ilocky))
- (nonnull instancetype)initWithHex:(NSString * __nonnull)hex;
@end


@interface UIImage (SWIFT_EXTENSION(ilocky))
@end


@interface UIView (SWIFT_EXTENSION(ilocky))
- (void)showLoading;
- (void)hideLoading;
@end

@class UIStoryboardSegue;

@interface UIViewController (SWIFT_EXTENSION(ilocky))
- (IBAction)unwindToViewController:(UIStoryboardSegue * __nonnull)sender;
@end

#pragma clang diagnostic pop
