// Generated by Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import CoreBluetooth;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC6ILocky6Device")
@interface Device : NSObject
@property (nonatomic, readonly, copy) NSString * __null_unspecified NAME_PREF;
@property (nonatomic, readonly, copy) NSString * __null_unspecified NAME;
@property (nonatomic, readonly, copy) NSString * __null_unspecified ILOCKY_ID;
@property (nonatomic, readonly, copy) NSString * __null_unspecified MACADDR;
@property (nonatomic, readonly, copy) NSString * __null_unspecified FW_VERSION;
@property (nonatomic, readonly, copy) NSString * __null_unspecified STARRED;
@property (nonatomic, readonly, copy) NSString * __null_unspecified CREATED_TIME;
- (nonnull instancetype)initWithILocky_id:(NSString * __nonnull)iLocky_id name:(NSString * __nonnull)name MACAddr:(NSString * __nonnull)MACAddr fwVersion:(NSString * __nonnull)fwVersion OBJC_DESIGNATED_INITIALIZER;
- (NSString * __nullable)getName;
+ (Device * __nullable)bluetoothNameToiLockyDevice:(NSString * __nullable)peripheralName;
@end

@protocol ILockyEventDelegate;
@class NSString;
@class ILockyPassport;

SWIFT_CLASS("_TtC6ILocky6ILocky")
@interface ILocky : NSObject
+ (void)setBackground:(BOOL)isBackground;
+ (void)setEventDelegate:(id <ILockyEventDelegate> __nonnull)delegate;
+ (void)track:(NSString * __nonnull)event;
+ (void)trackWaitTime:(ILockyPassport * __nonnull)passport success:(BOOL)success wait_time:(NSInteger)wait_time;
+ (void)track:(NSString * __nonnull)event prop:(NSDictionary<NSString *, id> * __null_unspecified)prop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CBCentralManager;
@class CBPeripheral;
@class NSNumber;
@class NSError;
@class CBService;
@class CBCharacteristic;
@class CBPeripheralManager;

SWIFT_CLASS("_TtC6ILocky16ILockyBLEManager")
@interface ILockyBLEManager : NSObject <CBPeripheralManagerDelegate, CBCentralManagerDelegate, CBPeripheralDelegate>
@property (nonatomic, strong) id <ILockyEventDelegate> __nullable iLockyEventDelegate;
- (void)centralManager:(CBCentralManager * __nonnull)central didDiscoverPeripheral:(CBPeripheral * __nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * __nonnull)advertisementData RSSI:(NSNumber * __nonnull)RSSI;
- (void)centralManager:(CBCentralManager * __nonnull)central didConnectPeripheral:(CBPeripheral * __nonnull)peripheral;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didDiscoverServices:(NSError * __nullable)error;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * __nonnull)service error:(NSError * __nullable)error;
- (void)peripheral:(CBPeripheral * __nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * __nonnull)characteristic error:(NSError * __nullable)error;
- (void)centralManagerDidUpdateState:(CBCentralManager * __nonnull)central;
- (void)centralManager:(CBCentralManager * __nonnull)central didFailToConnectPeripheral:(CBPeripheral * __nonnull)peripheral error:(NSError * __nullable)error;
- (void)centralManager:(CBCentralManager * __nonnull)central willRestoreState:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)peripheralManager:(CBPeripheralManager * __nonnull)_peripheral willRestoreState:(NSDictionary<NSString *, id> * __nonnull)dict;
- (void)peripheralManagerDidUpdateState:(CBPeripheralManager * __nonnull)peripheral;
@end


SWIFT_PROTOCOL("_TtP6ILocky19ILockyEventDelegate_")
@protocol ILockyEventDelegate
- (void)onPassportUsed:(ILockyPassport * __nonnull)passport;
- (void)onILockyAccessSuccess:(ILockyPassport * __nonnull)passport;
- (void)onILockyAccessFail:(ILockyPassport * __nonnull)passport;
- (void)onNotCloseEnough;
@end


SWIFT_CLASS("_TtC6ILocky14ILockyPassport")
@interface ILockyPassport : NSObject
+ (NSString * __null_unspecified)DEFAULT_PASSPORT_NAME;
+ (NSString * __null_unspecified)ILockyPassportErrorDomain;
+ (NSString * __null_unspecified)ACTION_TYPE;
+ (NSString * __null_unspecified)PASSPORT_NAME;
+ (NSString * __null_unspecified)ILOCKY_ID;
+ (NSString * __null_unspecified)DEVICE_UUID;
+ (NSString * __null_unspecified)START_TIME;
+ (NSString * __null_unspecified)END_TIME;
+ (NSString * __null_unspecified)TIMES_LIMIT;
+ (NSString * __null_unspecified)TIMES;
+ (NSString * __null_unspecified)REVOKE_PAST;
+ (NSString * __null_unspecified)SIGNATURE;
+ (NSString * __null_unspecified)VALID;
+ (NSString * __null_unspecified)LAST_TIME_STAMP;
+ (NSString * __null_unspecified)SERVER_PASSPORT;
+ (NSString * __null_unspecified)SERVER_PASSPORT_ID;
+ (NSString * __null_unspecified)SERVER_ILOCKY_ID;
+ (NSString * __null_unspecified)SERVER_DEVICE_UUID;
+ (NSString * __null_unspecified)SERVER_START_TIME;
+ (NSString * __null_unspecified)SERVER_END_TIME;
+ (NSString * __null_unspecified)SERVER_TIMES_LIMIT;
+ (NSString * __null_unspecified)SERVER_REVOKE_LEGACY;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_LOW_SECURITY_OPEN;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_DFU_OTA;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_INITIAL;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_RESET;
+ (NSString * __null_unspecified)SERVER_ACTION_TYPE_FACTORY_RESET;
+ (ILockyPassport * __nonnull)Builder;
- (ILockyPassport * __nonnull)setActionType:(NSInteger)type;
- (ILockyPassport * __nonnull)setPassportName:(NSString * __nonnull)name;
- (ILockyPassport * __nonnull)setDeviceId:(NSString * __nonnull)id;
- (ILockyPassport * __nonnull)setILockyId:(NSString * __nonnull)id;
- (ILockyPassport * __nonnull)setStartTime:(int64_t)time;
- (ILockyPassport * __nonnull)setEndTime:(int64_t)time;
- (ILockyPassport * __nonnull)setTimes:(NSInteger)times;
- (ILockyPassport * __nonnull)setRevokePast:(BOOL)revoke;
- (ILockyPassport * __nonnull)setSignature:(NSString * __nonnull)signature;
- (NSString * __null_unspecified)getILockyID;
- (NSString * __nullable)getPassportName;
- (NSInteger)getActionType;
- (NSInteger)getTimes;
- (NSInteger)getTimesLimit;
- (int64_t)getStartTime;
- (int64_t)getEndTime;
- (NSString * __nonnull)toJSONString;
+ (NSArray<ILockyPassport *> * __nonnull)getAlliLockyPassports;
+ (void)initialize;
+ (void)refreshValidStatus;
+ (NSString * __nonnull)getDeviceUuid;
+ (void)flush;
+ (void)removeAllInvalidPassports;
+ (void)importILockyPassport:(ILockyPassport * __nonnull)iLockyPassport error:(NSError * __nullable * __null_unspecified)error;
+ (ILockyPassport * __nullable)getValidPassport:(NSString * __nonnull)iLocky_id;
- (BOOL)isValid;
+ (BOOL)removePassport:(ILockyPassport * __null_unspecified)passport;
- (BOOL)isSame:(ILockyPassport * __nonnull)passport;
+ (void)importPassport:(NSString * __nonnull)content error:(NSError * __nullable * __null_unspecified)error;
@end

#pragma clang diagnostic pop
